# Generated by Django 3.2.5 on 2023-07-30 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplierpay_gst',
            fields=[
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='supplierpay_estimate',
            fields=[
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='customerpay_gst',
            fields=[
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Description', models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_gst')),
            ],
        ),
        migrations.CreateModel(
            name='customerpay_estimate',
            fields=[
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Description', models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_estimate')),
            ],
        ),
        migrations.AddIndex(
            model_name='supplierpay_estimate',
            index=models.Index(fields=['supplier_name', 'id'], name='payments_su_supplie_c1495c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpay_estimate',
            index=models.Index(fields=['customer_name', 'id'], name='payments_cu_custome_777eec_idx'),
        ),
    ]
