# Generated by Django 3.2.5 on 2023-07-25 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_estimate',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_gst',
            fields=[
                ('customerid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='customeraccount_gst',
            fields=[
                ('amount', models.FloatField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_gst')),
            ],
        ),
        migrations.CreateModel(
            name='customeraccount_estimate',
            fields=[
                ('amount', models.FloatField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_estimate')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer_estimate',
            index=models.Index(fields=['id', 'fullname'], name='customer_cu_id_10dac7_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount_estimate',
            index=models.Index(fields=['id', 'customer_name'], name='customer_cu_id_ef80ca_idx'),
        ),
    ]
