# Generated by Django 3.2.5 on 2023-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_estimate',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer_gst',
            name='customerid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
