# Generated by Django 4.2.4 on 2023-08-27 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230802_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_estimate',
            name='contactno',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[789]\\d{9}$')]),
        ),
    ]
