# Generated by Django 4.2.4 on 2023-09-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_estimate_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount_estimate',
            name='customer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_estimate'),
        ),
        migrations.AlterField(
            model_name='customeraccount_gst',
            name='customer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_gst'),
        ),
    ]
