# Generated by Django 3.2.5 on 2022-10-01 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phone_no', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('GSTNO', models.CharField(max_length=50)),
                ('Bank_name', models.CharField(max_length=50)),
                ('Bank_AC', models.CharField(max_length=50)),
                ('IFSC_Code', models.CharField(max_length=50)),
                ('Branch_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'id'], name='pages_profi_user_id_90b8de_idx'),
        ),
    ]
