# Generated by Django 3.2.5 on 2022-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'id'], name='pages_profi_user_id_90b8de_idx'),
        ),
    ]
