# Generated by Django 3.2.5 on 2023-07-29 02:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate_Purchase',
            fields=[
                ('Bill_no', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Total_amount', models.FloatField()),
                ('Due_amount', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='estimatepurchase_Product',
            fields=[
                ('Bill_no', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('dis', models.FloatField()),
                ('netrate', models.FloatField()),
                ('total', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='gstpurchase_Product',
            fields=[
                ('Bill_no', models.IntegerField()),
                ('hsncode', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('gstp', models.FloatField()),
                ('gstamt', models.FloatField()),
                ('total', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GST_Purchase',
            fields=[
                ('Bill_no', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('CGST', models.FloatField()),
                ('SGST', models.FloatField()),
                ('IGST', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst')),
            ],
        ),
        migrations.AddIndex(
            model_name='estimatepurchase_product',
            index=models.Index(fields=['Bill_no', 'id', 'product_name'], name='purchase_es_Bill_no_720757_idx'),
        ),
        migrations.AddField(
            model_name='estimate_purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate'),
        ),
        migrations.AddIndex(
            model_name='estimate_purchase',
            index=models.Index(fields=['Bill_no', 'id', 'supplier'], name='purchase_es_Bill_no_d0294c_idx'),
        ),
    ]
