# Generated by Django 4.2.4 on 2023-10-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_estimate_purchase_bill_number_gst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estimate_purchase_bill_number_gst',
            new_name='Gst_purchase_bill_number',
        ),
    ]
