# Generated by Django 4.2.4 on 2023-10-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_rename_estimate_purchase_bill_number_gst_gst_purchase_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gst_purchase',
            name='pdf_invoice',
            field=models.FileField(blank=True, null=True, upload_to='Purchase_Invoice/'),
        ),
    ]
