# Generated by Django 3.2.5 on 2021-09-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dailyexpense_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyexpense_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyincome_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyincome_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='estimatepurchase_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('dis', models.FloatField()),
                ('netrate', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='gstpurchase_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('hsncode', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('gstp', models.FloatField()),
                ('gstamt', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='gstsales_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('hsncode', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('gstp', models.FloatField()),
                ('gstamt', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_categ', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('store_location', models.CharField(max_length=50)),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_categ', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('store_location', models.CharField(max_length=50)),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='supplierpay_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='supplierpay_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='supplieraccount_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='supplieraccount_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product_gst')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product_estimate')),
            ],
        ),
        migrations.AddField(
            model_name='product_gst',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst'),
        ),
        migrations.AddField(
            model_name='product_estimate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_estimate'),
        ),
        migrations.CreateModel(
            name='gstsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('CGST', models.FloatField()),
                ('SGST', models.FloatField()),
                ('IGST', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_gst')),
            ],
        ),
        migrations.CreateModel(
            name='GST_Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('CGST', models.FloatField()),
                ('SGST', models.FloatField()),
                ('IGST', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Total_amount', models.FloatField()),
                ('Due_amount', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate_Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Total_amount', models.FloatField()),
                ('Due_amount', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='customerpay_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Description', models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_gst')),
            ],
        ),
        migrations.CreateModel(
            name='customerpay_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('round_off', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Description', models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_estimate')),
            ],
        ),
        migrations.CreateModel(
            name='customeraccount_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_gst')),
            ],
        ),
        migrations.CreateModel(
            name='customeraccount_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_estimate')),
            ],
        ),
    ]
