# Generated by Django 3.2.5 on 2023-07-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount_estimate',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customeraccount_gst',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='customerpay_estimate',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_estimate'),
        ),
        migrations.AlterField(
            model_name='customerpay_gst',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_gst'),
        ),
        migrations.AlterField(
            model_name='estimate_sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_estimate'),
        ),
        migrations.AlterField(
            model_name='gstsale',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_gst'),
        ),
        migrations.DeleteModel(
            name='Customer_estimate',
        ),
        migrations.DeleteModel(
            name='Customer_gst',
        ),
        migrations.DeleteModel(
            name='customeraccount_estimate',
        ),
        migrations.DeleteModel(
            name='customeraccount_gst',
        ),
    ]
