# Generated by Django 3.2.5 on 2021-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_purchase',
            name='supplier_name',
            field=models.CharField(max_length=50),
        ),
    ]
