# Generated by Django 3.2.5 on 2021-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estimatesales_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('dis', models.FloatField()),
                ('netrate', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
