# Generated by Django 3.2.5 on 2022-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_estimate',
            old_name='contactno',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer_estimate',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='customer_estimate',
            name='fullname',
        ),
        migrations.AddField(
            model_name='customer_estimate',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer_estimate',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='customer_estimate',
            index=models.Index(fields=['id', 'first_name', 'last_name'], name='dashboard_c_id_b45204_idx'),
        ),
    ]
