# Generated by Django 3.2.5 on 2022-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220522_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_estimate',
            name='cusotmer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
