# Generated by Django 3.2.5 on 2023-07-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('dashboard', '0002_auto_20230725_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieraccount_estimate',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='supplieraccount_gst',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='estimate_purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate'),
        ),
        migrations.AlterField(
            model_name='gst_purchase',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst'),
        ),
        migrations.AlterField(
            model_name='product_estimate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate'),
        ),
        migrations.AlterField(
            model_name='product_gst',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst'),
        ),
        migrations.AlterField(
            model_name='supplierpay_estimate',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate'),
        ),
        migrations.AlterField(
            model_name='supplierpay_gst',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst'),
        ),
        migrations.DeleteModel(
            name='Supplier_estimate',
        ),
        migrations.DeleteModel(
            name='Supplier_gst',
        ),
        migrations.DeleteModel(
            name='supplieraccount_estimate',
        ),
        migrations.DeleteModel(
            name='supplieraccount_gst',
        ),
    ]
