# Generated by Django 3.2.5 on 2021-07-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_gst_purchase_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_purchase',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst'),
        ),
    ]
