# Generated by Django 3.2.5 on 2021-12-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_estimatesales_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supplieraccount_estimate',
        ),
    ]
