# Generated by Django 3.2.5 on 2023-07-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230726_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_gst',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stock_estimate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock_gst',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_estimate',
        ),
        migrations.DeleteModel(
            name='Product_gst',
        ),
        migrations.DeleteModel(
            name='Stock_estimate',
        ),
        migrations.DeleteModel(
            name='Stock_gst',
        ),
    ]
