# Generated by Django 3.2.5 on 2021-12-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_supplieraccount_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplieraccount_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_estimate')),
            ],
        ),
    ]
