# Generated by Django 3.2.5 on 2021-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_gst_purchase_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gstsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('CGST', models.FloatField()),
                ('SGST', models.FloatField()),
                ('IGST', models.FloatField()),
                ('Round_off', models.FloatField()),
                ('Grand_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='gstsales_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('hsncode', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('qty', models.IntegerField()),
                ('gstp', models.FloatField()),
                ('gstamt', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
