# Generated by Django 3.2.5 on 2023-07-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230728_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_purchase',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='estimatepurchase_Product',
        ),
        migrations.RemoveField(
            model_name='gst_purchase',
            name='supplier_name',
        ),
        migrations.DeleteModel(
            name='gstpurchase_Product',
        ),
        migrations.DeleteModel(
            name='Estimate_Purchase',
        ),
        migrations.DeleteModel(
            name='GST_Purchase',
        ),
    ]
