# Generated by Django 3.2.5 on 2022-05-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220522_1415'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer_estimate',
            index=models.Index(fields=['customerid', 'id', 'fullname'], name='dashboard_c_custome_64e027_idx'),
        ),
    ]
