# Generated by Django 3.2.5 on 2021-07-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_gstsale_gstsales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstsale',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_gst'),
        ),
    ]
