# Generated by Django 3.2.5 on 2022-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customer_estimate_dashboard_c_custome_64e027_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customeraccount_estimate',
            index=models.Index(fields=['id', 'customer_name'], name='dashboard_c_id_64db37_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpay_estimate',
            index=models.Index(fields=['customer_name', 'id'], name='dashboard_c_custome_3448cd_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate_purchase',
            index=models.Index(fields=['Bill_no', 'id', 'supplier'], name='dashboard_e_Bill_no_ade141_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate_sales',
            index=models.Index(fields=['Bill_no', 'customer', 'id'], name='dashboard_e_Bill_no_f2992f_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatepurchase_product',
            index=models.Index(fields=['Bill_no', 'id', 'product_name'], name='dashboard_e_Bill_no_5f39ef_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatesales_product',
            index=models.Index(fields=['Bill_no', 'id', 'product_name'], name='dashboard_e_Bill_no_3c8a50_idx'),
        ),
        migrations.AddIndex(
            model_name='product_estimate',
            index=models.Index(fields=['product_name', 'id', 'supplier'], name='dashboard_p_product_92f855_idx'),
        ),
        migrations.AddIndex(
            model_name='stock_estimate',
            index=models.Index(fields=['product', 'id'], name='dashboard_s_product_d2ed95_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier_estimate',
            index=models.Index(fields=['supplierid', 'id'], name='dashboard_s_supplie_a3e2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount_estimate',
            index=models.Index(fields=['supplier_name', 'id'], name='dashboard_s_supplie_4715f9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpay_estimate',
            index=models.Index(fields=['supplier_name', 'id'], name='dashboard_s_supplie_3e4539_idx'),
        ),
    ]
