# Generated by Django 3.2.5 on 2023-07-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230729_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_sales',
            name='customer',
        ),
        migrations.DeleteModel(
            name='estimatesales_Product',
        ),
        migrations.RemoveField(
            model_name='gstsale',
            name='customer_name',
        ),
        migrations.DeleteModel(
            name='gstsales_Product',
        ),
        migrations.DeleteModel(
            name='Estimate_sales',
        ),
        migrations.DeleteModel(
            name='gstsale',
        ),
    ]
