# Generated by Django 3.2.5 on 2023-07-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230730_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpay_gst',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='supplierpay_estimate',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='supplierpay_gst',
            name='supplier_name',
        ),
        migrations.DeleteModel(
            name='customerpay_estimate',
        ),
        migrations.DeleteModel(
            name='customerpay_gst',
        ),
        migrations.DeleteModel(
            name='supplierpay_estimate',
        ),
        migrations.DeleteModel(
            name='supplierpay_gst',
        ),
    ]
