# Generated by Django 3.2.5 on 2021-08-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customerpay_gst_supplierpay_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpay_gst',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer_gst'),
        ),
        migrations.AlterField(
            model_name='supplierpay_gst',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier_gst'),
        ),
    ]
