# Generated by Django 3.2.5 on 2023-07-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20230730_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category_estimate',
        ),
        migrations.DeleteModel(
            name='category_gst',
        ),
        migrations.DeleteModel(
            name='dailyexpense_estimate',
        ),
        migrations.DeleteModel(
            name='dailyexpense_gst',
        ),
        migrations.DeleteModel(
            name='dailyincome_estimate',
        ),
        migrations.DeleteModel(
            name='dailyincome_gst',
        ),
    ]
