# Generated by Django 3.2.5 on 2021-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210801_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpay_estimate',
            name='round_off',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpay_gst',
            name='round_off',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
