# Generated by Django 3.2.5 on 2021-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210905_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpay_estimate',
            name='round_off',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpay_gst',
            name='round_off',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
