# Generated by Django 4.2.4 on 2023-08-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_auto_20230730_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashborad_data_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='dashboard Estimate Data', max_length=50)),
                ('today_estimate_sale', models.FloatField(blank=True, default=0, null=True)),
                ('total_estimate_sale', models.FloatField(blank=True, default=0, null=True)),
                ('current_month_estimate_sale', models.FloatField(blank=True, default=0, null=True)),
                ('previous_month_estimate_sale', models.FloatField(blank=True, default=0, null=True)),
                ('today_estimate_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('total_estimate_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('current_month_estimate_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('previous_month_estimate_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('current_month_profit', models.FloatField(blank=True, default=0, null=True)),
                ('previous_month_profit', models.FloatField(blank=True, default=0, null=True)),
                ('total_profit', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
