# Generated by Django 3.2.5 on 2021-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210905_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpay_estimate',
            name='Description',
            field=models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpay_gst',
            name='Description',
            field=models.CharField(blank=True, default='Cash on Hand', max_length=100, null=True),
        ),
    ]
