# Generated by Django 3.2.5 on 2023-07-26 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_estimate',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_gst',
            fields=[
                ('supplierid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplieraccount_gst',
            fields=[
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='supplieraccount_estimate',
            fields=[
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate')),
            ],
        ),
        migrations.AddIndex(
            model_name='supplier_estimate',
            index=models.Index(fields=['id', 'fullname'], name='supplier_su_id_f40634_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount_estimate',
            index=models.Index(fields=['supplier_name', 'id'], name='supplier_su_supplie_451302_idx'),
        ),
    ]
