# Generated by Django 4.2.4 on 2023-09-19 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_estimate_sales_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_number',
            fields=[
                ('last_bill_number', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
