# Generated by Django 4.2.4 on 2023-09-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_bill_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill_number',
            new_name='Estimate_sale_bill_number',
        ),
    ]
