# Generated by Django 4.2.4 on 2023-10-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customeraccount_estimate_customer_name_and_more'),
        ('sales', '0005_gst_sale_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstsale',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_sales', to='customer.customer_gst'),
        ),
    ]
