# Generated by Django 4.2.4 on 2023-09-19 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0003_alter_supplieraccount_estimate_supplier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_estimate',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('product_categ', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('purchase_price', models.FloatField(blank=True, default=0, null=True)),
                ('store_location', models.CharField(max_length=50)),
                ('minimum_stock', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_gst',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('product_categ', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('store_location', models.CharField(max_length=50)),
                ('minimum_stock', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_gst')),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('product_type', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_gst',
            fields=[
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product_gst')),
            ],
        ),
        migrations.CreateModel(
            name='product_required_to_manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacture_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_products', to='products.product_estimate')),
                ('required_products', models.ManyToManyField(blank=True, related_name='required_products_for_manufacture', to='products.product_estimate')),
            ],
        ),
        migrations.AddField(
            model_name='product_estimate',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_type'),
        ),
        migrations.AddField(
            model_name='product_estimate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_estimate'),
        ),
        migrations.CreateModel(
            name='Stock_estimate',
            fields=[
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product_estimate')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'id'], name='products_st_product_f5e8b7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product_estimate',
            index=models.Index(fields=['product_name', 'id', 'supplier'], name='products_pr_product_c7f07d_idx'),
        ),
    ]
