# Generated by Django 4.2.4 on 2023-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_estimate',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
