# Generated by Django 4.2.4 on 2023-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_estimate',
            name='product_categ',
            field=models.CharField(default='nothing', max_length=50),
            preserve_default=False,
        ),
    ]
