# Generated by Django 4.2.4 on 2023-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_estimate_product_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_estimate',
            name='product_categ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
