# Generated by Django 4.2.4 on 2023-09-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type_product_estimate_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_required_to_manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacture_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_estimate')),
                ('required_products', models.ManyToManyField(blank=True, to='products.product_required_to_manufacture')),
            ],
        ),
    ]
