# Generated by Django 4.2.4 on 2023-09-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_estimate_product_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_estimate',
            name='product_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_category'),
        ),
    ]
