# Generated by Django 4.2.4 on 2023-10-07 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_estimate_product_categ'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category_gst',
            fields=[
                ('product_category', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_type_gst',
            fields=[
                ('product_type', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product_estimate',
            name='products_pr_product_c7f07d_idx',
        ),
        migrations.AddField(
            model_name='product_gst',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='product_estimate',
            index=models.Index(fields=['id', 'supplier'], name='products_pr_id_0be5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product_gst',
            index=models.Index(fields=['id', 'supplier'], name='products_pr_id_407fda_idx'),
        ),
        migrations.AddIndex(
            model_name='stock_gst',
            index=models.Index(fields=['product', 'id'], name='products_st_product_f11c44_idx'),
        ),
        migrations.AddField(
            model_name='product_gst',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_type_gst'),
        ),
        migrations.AlterField(
            model_name='product_gst',
            name='product_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_category_gst'),
        ),
    ]
