# Generated by Django 4.2.4 on 2023-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_required_to_manufacture_manufacture_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_required_to_manufacture',
            name='required_products',
            field=models.ManyToManyField(blank=True, related_name='required_products_for_manufacture', to='products.product_estimate'),
        ),
    ]
