# Generated by Django 4.2.4 on 2023-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_required_to_manufacture_required_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_estimate',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
