# Generated by Django 4.2.4 on 2023-10-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_product_required_to_manufacture_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_required_to_manufacture_gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacture_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_products_gst', to='products.product_gst')),
                ('required_products', models.ManyToManyField(blank=True, related_name='required_products_for_manufacture_gst', to='products.product_gst')),
            ],
        ),
    ]
