# Generated by Django 4.2.4 on 2023-10-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_stock_gst_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_estimate',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_estimate', to='products.product_estimate'),
        ),
    ]
